### PR TITLE
signature_latte added

### PR DESCRIPTION
**Pull request by sugandha1591**

### CODE REVIEW

**Comment by Aniketjain4717** [comment]
Great job on adding the signature latte recipe! However, it would be helpful to update the relevant menu file to include this new item.
- Signature Latte: Our special blend of espresso

**Comment by sugandha1591** [comment]
I've added the reference to the Signature Latte in the branch1 menu as requested. Please review the updated changes. Thank you!
@Aniketjain4717

**Review by Aniketjain4717 — COMMENTED** [review]
Approved

**Review by Aniketjain4717 — COMMENTED** [review]
Approved

**Pull request merged**
